### ISSUE TITLE
Zmiana kolumny 'Stan'

### ISSUE THREAD

**Issue by dolejnik** [kret11/IT_APP_WT1855_PIFS#2]
Powinien to być enum, a na webie przy aktualizacji zamówienia chciałbym widzieć selecta, żeby sobie wybrać odpowiedni.
Dodatkowo dwie z opcji (najlepiej 'odebrano' i 'anulowano') powinny kończyć cykl życia zamówienia, wysyłać maila i przerzucać zamówienie do osobnej listy - archiwum.

**Comment by Tatarak** [comment]
Może być enum, ale w takim razie trzeba zdefiniować wszystkie możliwe stany. Ewentualnie zrobić tabelę w bazie danych, do której SuperAdmin będzie mógł dodawać/usuwać stany, a zwykły pracownik będzie mógł tylko wybierać z listy dostępnych.

**Comment by dolejnik** [comment]
Myślę, że spokojnie można zdefiniować z góry dostępne statusy. Nie zrobi się przynajmniej bałagan.
Moja propozycja:
przyjęte, aktualizacja, oczekiwanie na dostarczenie części, naprawiane, kontakt z klientem (te mogą być na szczycie listy), gotowe do odbioru, zakończono, anulowane

**Comment by Tatarak** [comment]
Należy przeanalizować, czy obecnie dostępne stany są dobre i wystarczające.
