### ISSUE TITLE
Dodanie pola 'Nazwa' oraz 'Uwagi' do Usera

### ISSUE THREAD

**Issue by dolejnik** [kret11/IT_APP_WT1855_PIFS#6]
User powinien mieć jedno dodatkowe opcjonalne pole: Uwagi - w tym polu będzie można wpisać sobie numer telefonu do klienta albo ewentualne notatki: preferencje czy adres.
Pole to powinno się pojawiać na widoku szczegółowym zamówienia.

Identyfikacja powinna się odbywać po unikatowej nazwie: Imię+nazwisko lub nazwa firmy.

**Comment by Tatarak** [comment]
Czy wystarczy jedno dodatkowe pole na wszystkie informacje? Może lepiej dodać osobne pola na imię nazwisko nr tel. i adres?

**Comment by dolejnik** [comment]
Dwa pola są ok. Nazwa i Uwagi
